default: &default
  adapter: postgresql
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  encoding: unicode
  pool:  <%= ENV['DATABASE_POOL_SIZE'] || 5 %>

development:
  <<: *default
  database: office_management-development

test:
  <<: *default
  database: office_management-test